name: Deploy Docs

on:
  push:
    branches: [main]
    paths:
      - '**'
      - '!.github/**'
      - '.github/workflows/build-docs.yaml'
  pull_request:
    paths:
      - '**'
      - '!.github/**'
      - '.github/workflows/build-docs.yaml'

#  schedule:
#    # Runs every Sunday at 01 AM ET - 5:00 UTC
#    - cron: '0 5 * * 0'

  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6

      - name: Test that docs build without error
        if: github.event_name == 'pull_request'
        run: uv run --group docs mkdocs build --strict

      - name: Deploy docs to GitHub Pages
        if: github.event_name == 'push'
        run: uv run --group docs mkdocs gh-deploy --strict --force